duplicate requirement from base.txt which causes pip install errors
```
Step 5/6 : RUN pip install -r /requirements/celery.txt
 ---> Running in b829968de393
Double requirement given: pytz==2016.4 (from -r /requirements/celery.txt (line 9)) (already in pytz==2016.10 (from -r /requirements/base.txt (line 38)), name='pytz')
ERROR: Service 'celery' failed to build: The command '/bin/sh -c pip install -r /requirements/celery.txt' returned a non-zero code: 1
```